=== SMAC/smaclib/smaclib/modules/archiver/workflows/workflow.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:sw="http://smac.hefr.ch/archiver/workflow"
	targetNamespace="http://smac.hefr.ch/archiver/workflow"
	elementFormDefault="qualified">
	
	<xs:include schemaLocation="triggers.xsd"></xs:include>
	
	<xs:complexType name="tag" mixed="true">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="strong" type="sw:tag"/>
			<xs:element name="em" type="sw:tag"/>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="html" mixed="true">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="p" type="sw:tag"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="workflow-meta">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="author" type="xs:string"/>
			<xs:element name="description" type="sw:html"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="workflow-task">
		<xs:sequence minOccurs="0" maxOccurs="unbounded">
			<xs:element name="param">
				<xs:complexType mixed="true">
					<xs:attribute name="name" use="required" type="xs:NMTOKEN"/>
					<xs:attribute name="type" use="optional" default="str">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="str"/>
								<xs:enumeration value="int"/>
								<xs:enumeration value="float"/>
								<xs:enumeration value="unicode"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="name" type="xs:ID" use="required"/>
		<xs:attribute name="depends-on" type="xs:IDREFS" use="optional"/>
		<xs:attribute name="class" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="workflow-root">
		<xs:sequence>
			<xs:element name="meta" type="sw:workflow-meta"/>
			<xs:element name="trigger" type="sw:predicate-group"/>
			<xs:element name="task" type="sw:workflow-task" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:element name="workflow" type="sw:workflow-root"/>
</xs:schema>

=== SMAC/smaclib/smaclib/modules/archiver/workflows/pdf_slideshow.xml
<?xml version="1.0" encoding="UTF-8"?>
<workflow
	xmlns="http://smac.hefr.ch/archiver/workflow"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://smac.hefr.ch/archiver/workflow workflow.xsd">

	<meta>
		<name>Slideshow processing</name>
		<author>Jonathan Stoppani</author>
		<description>
			<p>Processes all uploaded PDF slideshow documents by extracting the page images.</p>
		</description>
	</meta>
	
	<trigger>
		<role is="slideshow"/>
		<extension is="pdf"/>
	</trigger>
	
	<task name="generate-images"
		class="smaclib.modules.archiver.tasks.GenerateImages"/>
</workflow>

=== SMAC/smaclib/smaclib/modules/archiver/workflows/metadata.xml
<?xml version="1.0" encoding="UTF-8"?>
<workflow
	xmlns="http://smac.hefr.ch/archiver/workflow"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://smac.hefr.ch/archiver/workflow workflow.xsd">

	<meta>
		<name>Alignment processing</name>
		<author>Jonathan Stoppani</author>
		<description>
			<p>Processes all uploaded alignment files and moves them to the contrib root.</p>
		</description>
	</meta>
	
	<trigger>
		<role is="alignment"/>
		<extension is="xml"/>
	</trigger>
	
	<task name="move-to-root"
		class="smaclib.modules.archiver.tasks.archiveAlignment"/>
</workflow>

=== SMAC/smaclib/smaclib/modules/archiver/workflows/video.xml
<?xml version="1.0" encoding="UTF-8"?>
<workflow
	xmlns="http://smac.hefr.ch/archiver/workflow"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://smac.hefr.ch/archiver/workflow workflow.xsd">

	<meta>
		<name>Slideshow processing</name>
		<author>Jonathan Stoppani</author>
		<description>
			<p>Processes all uploaded slideshow documents by converting them to PDF files and extracting the page images.</p>
		</description>
	</meta>
	
	<trigger>
		<role is="video"/>
	</trigger>
	
	<task name="encode-to-flv"
		class="smaclib.modules.archiver.tasks.EncodeFLV"/>
</workflow>
